### ISSUE TITLE
Tag extra in "Categorie" 

### ISSUE THREAD

**Issue by Alexandru-Chindris** [profmancusoa/profmancusoa.github.io#55]
~~Ciao @gioele-mari, ti faccio notare che hai inserito dei tag extra nella sezione "Categorie" nel tuo articolo sul blog.
A presto, ciao!~~

(edit: problema globale)

![gioele](https://user-images.githubusercontent.com/89776299/198846585-cbf87d82-ce4b-418a-99e1-c73e58b1351b.png)

**Comment by Alexandru-Chindris** [comment]
@profmancusoa penso che ci sia un problema con la sezione "Categorie" del blog, in quanto in tutti i post vengono messe le categorie inserite da tutti

**Comment by profmancusoa** [comment]
?? direi di no:

- sotto il titolo dell'articolo vengono visualizzate solo le categorie dell'articolo stesso
- nel riquadro a destra categorie vengono sempre visualizzate tutte le categorie (per il momento senza nessuna funzionalità particolare)
